### ISSUE TITLE
Tabbed UI alterations.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/BetterDocs#150]
Move "Main Pane" to right of Code Pane and rename to "All".
Rename "Code Pane" to "Featured".

**Comment by amit-shar** [comment]
Plugin-start snapshot
![screenshot from 2015-05-28 16 45 54](https://cloud.githubusercontent.com/assets/11629465/7858865/923fa700-0559-11e5-9b63-a0eb4c295a2a.png)

**Comment by amit-shar** [comment]
After BetterDocs search 
![screenshot from 2015-05-28 16 52 06](https://cloud.githubusercontent.com/assets/11629465/7858949/25168d50-055a-11e5-998c-58e41b9a8918.png)
